name: React App Deployment-Practice

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Create React App Build
        run: npm run build

      - name: Trigger Render Deploy Hook
        env:
          DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          echo "Triggering deploy via Render Deploy Hook..."
          curl -X POST $DEPLOY_HOOK
